modLoader="javafml"
loaderVersion="[4,)"
license="All Rights Reserved"

[[mods]]
modId="upgradertemplates"
version="1.1.0"
displayName="Suluzuko's Smithing Templates"
displayURL="https://github.com/Suluzuko"
logoFile="logo.png"
credits="Head Coder - Suluzuko, Head Artist - Zacblazer"
authors="Suluzuko, Zacblazer"
description="A mod that aims to slow progression with 4 new smithing templates that are required to obtain armor and tools."

# Start of user code block mod configuration
# End of user code block mod configuration


# Start of user code block custom mixins
# End of user code block custom mixins

[[dependencies.upgradertemplates]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.176,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.upgradertemplates]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration